spring:
  application:
    name: climalert-asincronismo
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

    listener:
      simple:
        default-requeue-rejected: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: pruebaalertastp@gmail.com
    password: vipf phqk mhsf qpjl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

rest-weather:
  base-url: http://api.weatherapi.com/v1
  api-key: "88a9c8396c4d4c9f841152151260307"

climalert:
  events:
    exchange: clima.exchange
  alertas:
    queue: clima.alertas
    routing-key: alerta
